<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType><TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../src/Pancake/Services/PortableUpdateService.cs" Link="PortableUpdateService.cs" />
    <Compile Include="../../src/Pancake/Services/GitHubUpdateService.cs" Link="GitHubUpdateService.cs" />
    <Compile Include="../../src/Pancake/Services/ReleaseUpdateService.cs" Link="ReleaseUpdateService.cs" />
    <Compile Include="../../src/Pancake/Services/SplitUpdatePackage.cs" Link="SplitUpdatePackage.cs" />
    <Content Include="../../src/Pancake/Tools/7zip/**/*" Link="Tools/7zip/%(RecursiveDir)%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="../../src/Pancake/ApplyUpdate.ps1" Link="ApplyUpdate.ps1" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
